apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "ratings"
  title: "ratings"
  description: "Ratings Service"
  annotations:
    backstage.io/spectral-ruleset-url: https://raw.githubusercontent.com/contract-first-idp-qa/spectral-rules/main/ruleset.yaml
  links:
    - url: https://registry-apicurio-registry.apps.cluster-rvd25.rvd25.sandbox732.opentlc.com/ui/artifacts/com.redhat/ratings/versions/latest
      title: Apicurio Registry
      icon: web
    - url: https://microcks-microcks.apps.cluster-rvd25.rvd25.sandbox732.opentlc.com/#/services?name=ratings
      title: Microcks
    - url: https://microcks-microcks.apps.cluster-rvd25.rvd25.sandbox732.opentlc.com/rest/ratings/v1
      title: Mock
      icon: web
spec:
  type: openapi
  system: system:default/bookinfo
  owner: "group:default/backstage-admins"
  lifecycle: production
  definition:
    $openapi: https://github.com/contract-first-idp-qa/bookinfo-ratings-api/blob/main/specification.yaml